CREATE TABLE tmp_flats_history (
    ad_id               integer,
    house_id            integer,
    floor               smallint,
    rooms               smallint,
    street              text,
    street_type         varchar(9),
    house               text,
    town                smallint,
    total_floors        smallint,
    area                numeric,
    living_area         numeric,
    kitchen_area        numeric,
    house_type_id       smallint,
    ao_id               smallint,
    built               smallint,
    metro_id            smallint,
    km_do_metro         numeric(6,3),
    source_id           smallint,
    object_type_id      smallint,
    nedvigimost_type_id smallint,
    url                 text,
    person_type_id      smallint,
    price               numeric,
    time_source_created date,
    time_source_updated timestamp,
    avitoid             text,
    is_actual           smallint,
    description         text,
    UNIQUE (avitoid, source_id)
  );-- ON COMMIT DROP;